<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <fieldUpdates>
        <fullName>UpdateInterestDetailText</fullName>
        <field>Interest_Detail_Text__c</field>
        <formula>InterestValue__c</formula>
        <name>UpdateInterestDetailText</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>UpdateSummaryAffiliation</fullName>
        <field>Summary__c</field>
        <formula>ConcatenationAffiliation__c</formula>
        <name>UpdateSummaryAffiliation</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>UpdateSummaryAward</fullName>
        <field>Summary__c</field>
        <formula>ConcatenationAward__c</formula>
        <name>UpdateSummaryAward</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>UpdateSummaryBlackBaudRatings</fullName>
        <field>Summary__c</field>
        <formula>ConcatenationBlackBaudRatings__c</formula>
        <name>UpdateSummaryBlackBaudRatings</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>UpdateSummaryCharitableGiving</fullName>
        <field>Summary__c</field>
        <formula>ConcatenationCharitableGiving__c</formula>
        <name>UpdateSummaryCharitableGiving</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>UpdateSummaryEducation</fullName>
        <field>Summary__c</field>
        <formula>ConcatenationEducation__c</formula>
        <name>UpdateSummaryEducation</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>UpdateSummaryEmployment</fullName>
        <field>Summary__c</field>
        <formula>ConcatenationEmployment__c</formula>
        <name>UpdateSummaryEmployment</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>UpdateSummaryFinancial</fullName>
        <field>Summary__c</field>
        <formula>ConcatenationFinancial__c</formula>
        <name>UpdateSummaryFinancial</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>UpdateSummaryInterest</fullName>
        <field>Summary__c</field>
        <formula>ConcatenationInterest__c</formula>
        <name>UpdateSummaryInterest</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>UpdateSummaryMembership</fullName>
        <field>Summary__c</field>
        <formula>ConcatenationMembership__c</formula>
        <name>UpdateSummaryMembership</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>UpdateSummaryRatingCloseness</fullName>
        <field>Summary__c</field>
        <formula>ConcatenationRatingCloseness__c</formula>
        <name>UpdateSummaryRatingCloseness</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>UpdateSummaryTrustee</fullName>
        <field>Summary__c</field>
        <formula>ConcatenationTrustee__c</formula>
        <name>UpdateSummaryTrustee</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>UpdateSummaryVolunteering</fullName>
        <field>Summary__c</field>
        <formula>ConcatenationVolunteering__c</formula>
        <name>UpdateSummaryVolunteering</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Formula</operation>
        <protected>false</protected>
    </fieldUpdates>
    <rules>
        <fullName>UpdateInterestDetailText</fullName>
        <actions>
            <name>UpdateInterestDetailText</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Bios__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Interest</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>UpdateSummaryAffiliation</fullName>
        <actions>
            <name>UpdateSummaryAffiliation</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Bios__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Affiliation</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>UpdateSummaryAward</fullName>
        <actions>
            <name>UpdateSummaryAward</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Bios__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Award</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>UpdateSummaryBlackBaudRatings</fullName>
        <actions>
            <name>UpdateSummaryBlackBaudRatings</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Bios__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>BlackBaud Ratings</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>UpdateSummaryCharitableGiving</fullName>
        <actions>
            <name>UpdateSummaryCharitableGiving</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Bios__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Charitable Giving</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>UpdateSummaryEducation</fullName>
        <actions>
            <name>UpdateSummaryEducation</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Bios__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Education</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>UpdateSummaryEmployment</fullName>
        <actions>
            <name>UpdateSummaryEmployment</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Bios__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Employment</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>UpdateSummaryFinancial</fullName>
        <actions>
            <name>UpdateSummaryFinancial</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Bios__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Financial</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>UpdateSummaryInterest</fullName>
        <actions>
            <name>UpdateSummaryInterest</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Bios__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Interest</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>UpdateSummaryMembership</fullName>
        <actions>
            <name>UpdateSummaryMembership</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Bios__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Membership</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>UpdateSummaryRatingCloseness</fullName>
        <actions>
            <name>UpdateSummaryRatingCloseness</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Bios__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Rating/Closeness</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>UpdateSummaryTrustee</fullName>
        <actions>
            <name>UpdateSummaryTrustee</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Bios__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Trustee</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
    <rules>
        <fullName>UpdateSummaryVolunteering</fullName>
        <actions>
            <name>UpdateSummaryVolunteering</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Bios__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Volunteering</value>
        </criteriaItems>
        <triggerType>onAllChanges</triggerType>
    </rules>
</Workflow>
